server:
  port: 8080
spring:
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: test
    password:

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

  config:
    import:
      - classpath:/application-prod.yml
      - classpath:/application-kakao.yml


logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace